name: Build container

on:
  - pull_request

jobs:
  julia-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: make
      - name: Runtime Test   
        run: docker-compose run --rm julia julia -e 'using Pkg; Pkg.build(); Pkg.test()'
